package com.inzisoft.mobileid.sp.domain.code.model;

public enum GroupCode {
//	AUTH_TYPE, // PIN, BIO, FACE
//	INTERFACE_TYPE, // QR_MPM, QR_CPM, APP2APP, PUSH, BLE_QR_CPM, BLE_QR_MPM, NFC
//	PRESENT_TYPE, // DID_AUTH, DID_VP, ZKP_VP
//	STEP, // OPEN_TRANSACTION, ISSUE_PROFILE, VP_VERIFY, COMPLETE
//	SUBMIT_MODE, // INDIRECT, DIRECT, PROXY, P2P

	ID_TYPE, // DRIVING_LICENSE
	CHANNEL, // BRANCH, DEFAULT
}
